### PR TITLE
add mpls test

### PR DESCRIPTION
**Pull request by junpei-yoshino**
This dump&template data are cisco router netflow that has mpls information.
#5 is tested by this data (some field values are modified by binary editor).

### CODE REVIEW

**Comment by repeatedly** [comment]
@junpei-yoshino Could you rebase the branch? After merged #15, bransh has conflicts.

**Comment by junpei-yoshino** [comment]
git-rebase done!
Thank you.

**Comment by junpei-yoshino** [comment]
test this please

**Comment by repeatedly** [comment]
Thx!

**Pull request merged**
